/*
 * Novembro/Dezembro 2020.
 * Senai Fatesg Faculdade de Tecnologia
 * ADS - Análise e Desenvolvimento de Sistemas
 * Projeto Integrador - ADS3
 * Projeto Mula Car - aluguel de Veículos
 * Alunos: Aires Ribeiro, Gabriel Cunha, Lucas França e Rogério Reis
 */

package br.com.mulacar.app;

import br.com.mulacar.bll.*;
import br.com.mulacar.model.*;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class LocacaoVeiculosApp extends javax.swing.JDialog {
    CategoriaBll catBll;
    Categoria cat;
    MarcaBll marBll;
    Marca mar;
    ModeloBll modBll;
    Modelo mod;

    /**
     * Creates new form LocacaoVeiculosApp
     */
    public LocacaoVeiculosApp(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
            initComponents();
            catBll = new CategoriaBll();
        try {
            List<Categoria> listaCategoria = catBll.getConsultaCategorias();
            catBll.ordenaListaCategorias(listaCategoria);
            jComboBoxSelecaoCategoria.removeAllItems();
            jComboBoxSelecaoCategoria.addItem(" ");
            for (int pos = 0; pos < listaCategoria.size(); pos++) {
                cat = listaCategoria.get(pos);
                jComboBoxSelecaoCategoria.addItem(cat.getDescricao().toUpperCase());
//                jComboBoxSelecaoCategoria.addItem(cat.getId()+ " - " + cat.getDescricao().toUpperCase());
            }
            //LISTA MODELOS
            modBll = new ModeloBll();
            List<Modelo> listaModelo = modBll.getConsultaModelos();
            modBll.ordenaListaModelos(listaModelo);
            jComboBoxSelecaoModelo.removeAllItems();
            jComboBoxSelecaoModelo.addItem(" ");
            for (int pos = 0; pos < 10; pos++) {
                mod = listaModelo.get(pos);
                jComboBoxSelecaoModelo.addItem(mod.getDescricao().toUpperCase());
            }
            
            //LISTA MARCA
            marBll = new MarcaBll();
            List<Marca> listaMarca = marBll.getConsultaMarcas();
            marBll.ordenaListaMarcas(listaMarca);
            jComboBoxSelecaoMarca.removeAllItems();
            jComboBoxSelecaoMarca.addItem(" ");
            for (int i = 0; i < listaMarca.size(); i++) {
                mar = listaMarca.get(i);
                jComboBoxSelecaoMarca.addItem(mar.getDescricao().toUpperCase());
            }
   
            
        } catch (Exception ex) {
            Logger.getLogger(LocacaoVeiculosApp.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelSelecaoDoVeiculo = new javax.swing.JPanel();
        jLabel71 = new javax.swing.JLabel();
        jComboBoxSelecaoCategoria = new javax.swing.JComboBox();
        jLabel72 = new javax.swing.JLabel();
        jComboBoxSelecaoMarca = new javax.swing.JComboBox();
        jLabel85 = new javax.swing.JLabel();
        jComboBoxSelecaoModelo = new javax.swing.JComboBox();
        jButtonBuscarVeiculos = new javax.swing.JButton();
        jScrollPaneListaDeVeiculo = new javax.swing.JScrollPane();
        jTableListaDeVeiculos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanelDadosDoCliente = new javax.swing.JPanel();
        jScrollPaneListaDeClientes = new javax.swing.JScrollPane();
        jTableDadosDoCliente = new javax.swing.JTable();
        jScrollPaneDadosDoCliente = new javax.swing.JScrollPane();
        jTextAreaDadosDoCliente = new javax.swing.JTextArea();
        jTextFieldCpfCnpj = new javax.swing.JTextField();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jTextFieldNomeCliente = new javax.swing.JTextField();
        jLabel83 = new javax.swing.JLabel();
        jTextFieldRazaoSocial = new javax.swing.JTextField();
        jButtonBuscarCliente = new javax.swing.JButton();
        jButtonInserirCliente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanelDadosDoMotorista = new javax.swing.JPanel();
        jLabel73 = new javax.swing.JLabel();
        jTextFieldCpfCnpj1 = new javax.swing.JTextField();
        jLabel74 = new javax.swing.JLabel();
        jTextFieldNomeCliente1 = new javax.swing.JTextField();
        jButtonInserirMotorista = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButtonBuscarMotorista = new javax.swing.JButton();
        jScrollPaneDadosDoCliente1 = new javax.swing.JScrollPane();
        jTextAreaDadosDoCliente1 = new javax.swing.JTextArea();
        jScrollPaneListaDeClientes1 = new javax.swing.JScrollPane();
        jTableDadosDoCliente1 = new javax.swing.JTable();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanelDadosComplementares = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldSituacaoDoTanque = new javax.swing.JTextField();
        jTextFieldDataDaRetirada = new javax.swing.JTextField();
        jTextFieldDataDevolucaoPrevista = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaObservacao = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldKmInicial = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldValorSeguro = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldDataCadastro = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldUsuarioCadastro = new javax.swing.JTextField();
        jButtonFinalizarCadastro = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jCheckBoxAcessorioCadeirinha = new javax.swing.JCheckBox();
        jCheckBoxAcessorioSuporteParaBiciclet = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaComposicaoValores = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jButtonConfirmarComposicaoValores = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldValorLocacao = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextFieldValorAcessorios = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextFieldValorCaucao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonSelecaoVeiculo = new javax.swing.JButton();
        jButtonDadosDoCliente = new javax.swing.JButton();
        jButtonDadosDoMotorista = new javax.swing.JButton();
        jButtonDadosComplementares = new javax.swing.JButton();
        jButtonFecharLocacao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(".");
        setResizable(false);

        jPanelSelecaoDoVeiculo.setPreferredSize(new java.awt.Dimension(1137, 434));

        jLabel71.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel71.setText("Selecione a Categoria");

        jLabel72.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel72.setText("Selecione a Marca");

        jComboBoxSelecaoMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSelecaoMarcaActionPerformed(evt);
            }
        });

        jLabel85.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel85.setText("Selecione o  Modelo");

        jComboBoxSelecaoModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSelecaoModeloActionPerformed(evt);
            }
        });

        jButtonBuscarVeiculos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonBuscarVeiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mulacar/imagens/search-icon-16px.png"))); // NOI18N
        jButtonBuscarVeiculos.setText("Buscar");
        jButtonBuscarVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarVeiculosActionPerformed(evt);
            }
        });

        jTableListaDeVeiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Marca", "Modelo", "Tipo", "Categoria", "Nr.Passag.", "Ano Fab.", "Ano Mod.", "Km", "Placa", "Renavam", "Valor Diária", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneListaDeVeiculo.setViewportView(jTableListaDeVeiculos);
        if (jTableListaDeVeiculos.getColumnModel().getColumnCount() > 0) {
            jTableListaDeVeiculos.getColumnModel().getColumn(0).setMinWidth(50);
            jTableListaDeVeiculos.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTableListaDeVeiculos.getColumnModel().getColumn(0).setMaxWidth(50);
            jTableListaDeVeiculos.getColumnModel().getColumn(5).setMinWidth(70);
            jTableListaDeVeiculos.getColumnModel().getColumn(5).setPreferredWidth(70);
            jTableListaDeVeiculos.getColumnModel().getColumn(5).setMaxWidth(70);
            jTableListaDeVeiculos.getColumnModel().getColumn(6).setMinWidth(60);
            jTableListaDeVeiculos.getColumnModel().getColumn(6).setPreferredWidth(60);
            jTableListaDeVeiculos.getColumnModel().getColumn(6).setMaxWidth(60);
            jTableListaDeVeiculos.getColumnModel().getColumn(7).setMinWidth(60);
            jTableListaDeVeiculos.getColumnModel().getColumn(7).setPreferredWidth(60);
            jTableListaDeVeiculos.getColumnModel().getColumn(7).setMaxWidth(60);
            jTableListaDeVeiculos.getColumnModel().getColumn(8).setMinWidth(60);
            jTableListaDeVeiculos.getColumnModel().getColumn(8).setPreferredWidth(60);
            jTableListaDeVeiculos.getColumnModel().getColumn(8).setMaxWidth(60);
            jTableListaDeVeiculos.getColumnModel().getColumn(9).setMinWidth(90);
            jTableListaDeVeiculos.getColumnModel().getColumn(9).setPreferredWidth(90);
            jTableListaDeVeiculos.getColumnModel().getColumn(9).setMaxWidth(90);
            jTableListaDeVeiculos.getColumnModel().getColumn(10).setMinWidth(110);
            jTableListaDeVeiculos.getColumnModel().getColumn(10).setPreferredWidth(110);
            jTableListaDeVeiculos.getColumnModel().getColumn(10).setMaxWidth(110);
            jTableListaDeVeiculos.getColumnModel().getColumn(11).setMinWidth(80);
            jTableListaDeVeiculos.getColumnModel().getColumn(11).setPreferredWidth(80);
            jTableListaDeVeiculos.getColumnModel().getColumn(11).setMaxWidth(80);
            jTableListaDeVeiculos.getColumnModel().getColumn(12).setMinWidth(30);
            jTableListaDeVeiculos.getColumnModel().getColumn(12).setPreferredWidth(30);
            jTableListaDeVeiculos.getColumnModel().getColumn(12).setMaxWidth(30);
        }

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Escolha do Veículo");

        javax.swing.GroupLayout jPanelSelecaoDoVeiculoLayout = new javax.swing.GroupLayout(jPanelSelecaoDoVeiculo);
        jPanelSelecaoDoVeiculo.setLayout(jPanelSelecaoDoVeiculoLayout);
        jPanelSelecaoDoVeiculoLayout.setHorizontalGroup(
            jPanelSelecaoDoVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSelecaoDoVeiculoLayout.createSequentialGroup()
                .addGap(431, 431, 431)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPaneListaDeVeiculo)
            .addGroup(jPanelSelecaoDoVeiculoLayout.createSequentialGroup()
                .addGroup(jPanelSelecaoDoVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel71)
                    .addComponent(jComboBoxSelecaoCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(105, 105, 105)
                .addGroup(jPanelSelecaoDoVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxSelecaoMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel72))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addGroup(jPanelSelecaoDoVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSelecaoDoVeiculoLayout.createSequentialGroup()
                        .addComponent(jComboBoxSelecaoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127)
                        .addComponent(jButtonBuscarVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel85)))
        );
        jPanelSelecaoDoVeiculoLayout.setVerticalGroup(
            jPanelSelecaoDoVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSelecaoDoVeiculoLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(21, 21, 21)
                .addGroup(jPanelSelecaoDoVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel85)
                    .addComponent(jLabel72)
                    .addComponent(jLabel71))
                .addGap(1, 1, 1)
                .addGroup(jPanelSelecaoDoVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxSelecaoCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxSelecaoMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxSelecaoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarVeiculos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneListaDeVeiculo, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("", jPanelSelecaoDoVeiculo);

        jPanelDadosDoCliente.setPreferredSize(new java.awt.Dimension(1137, 434));

        jTableDadosDoCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("")));
        jTableDadosDoCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "CPF / CPNP", "Nome / Razão Social", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneListaDeClientes.setViewportView(jTableDadosDoCliente);
        if (jTableDadosDoCliente.getColumnModel().getColumnCount() > 0) {
            jTableDadosDoCliente.getColumnModel().getColumn(0).setMinWidth(50);
            jTableDadosDoCliente.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTableDadosDoCliente.getColumnModel().getColumn(0).setMaxWidth(50);
            jTableDadosDoCliente.getColumnModel().getColumn(1).setMinWidth(200);
            jTableDadosDoCliente.getColumnModel().getColumn(1).setPreferredWidth(200);
            jTableDadosDoCliente.getColumnModel().getColumn(1).setMaxWidth(200);
            jTableDadosDoCliente.getColumnModel().getColumn(3).setMinWidth(30);
            jTableDadosDoCliente.getColumnModel().getColumn(3).setPreferredWidth(30);
            jTableDadosDoCliente.getColumnModel().getColumn(3).setMaxWidth(30);
        }

        jScrollPaneDadosDoCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Do Cliente"));

        jTextAreaDadosDoCliente.setColumns(20);
        jTextAreaDadosDoCliente.setRows(5);
        jScrollPaneDadosDoCliente.setViewportView(jTextAreaDadosDoCliente);

        jLabel69.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel69.setText("Informe CPF ou CNPJ");

        jLabel70.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel70.setText("Informe Nome");

        jLabel83.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel83.setText("Informe Razão Social");

        jButtonBuscarCliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mulacar/imagens/search-icon-24px.png"))); // NOI18N
        jButtonBuscarCliente.setText("Buscar");

        jButtonInserirCliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonInserirCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mulacar/imagens/User-Clients-icon-24px.png"))); // NOI18N
        jButtonInserirCliente.setText("Inserir");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Dados do Cliente");

        javax.swing.GroupLayout jPanelDadosDoClienteLayout = new javax.swing.GroupLayout(jPanelDadosDoCliente);
        jPanelDadosDoCliente.setLayout(jPanelDadosDoClienteLayout);
        jPanelDadosDoClienteLayout.setHorizontalGroup(
            jPanelDadosDoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosDoClienteLayout.createSequentialGroup()
                .addGroup(jPanelDadosDoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDadosDoClienteLayout.createSequentialGroup()
                        .addGroup(jPanelDadosDoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDadosDoClienteLayout.createSequentialGroup()
                                .addComponent(jTextFieldCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDadosDoClienteLayout.createSequentialGroup()
                                .addComponent(jLabel69)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanelDadosDoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDadosDoClienteLayout.createSequentialGroup()
                                .addComponent(jTextFieldNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addGroup(jPanelDadosDoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel83)
                                    .addComponent(jTextFieldRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel70, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDadosDoClienteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(365, 365, 365)))
                .addGroup(jPanelDadosDoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonInserirCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanelDadosDoClienteLayout.createSequentialGroup()
                .addComponent(jScrollPaneListaDeClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneDadosDoCliente))
        );
        jPanelDadosDoClienteLayout.setVerticalGroup(
            jPanelDadosDoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDadosDoClienteLayout.createSequentialGroup()
                .addGroup(jPanelDadosDoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInserirCliente)
                    .addComponent(jLabel1))
                .addGroup(jPanelDadosDoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDadosDoClienteLayout.createSequentialGroup()
                        .addGroup(jPanelDadosDoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel83)
                            .addComponent(jLabel70)
                            .addComponent(jLabel69))
                        .addGap(1, 1, 1)
                        .addGroup(jPanelDadosDoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelDadosDoClienteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonBuscarCliente)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelDadosDoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPaneDadosDoCliente)
                    .addComponent(jScrollPaneListaDeClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("", jPanelDadosDoCliente);

        jPanelDadosDoMotorista.setPreferredSize(new java.awt.Dimension(1137, 434));

        jLabel73.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel73.setText("Informe CPF");

        jLabel74.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel74.setText("Informe Nome");

        jButtonInserirMotorista.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonInserirMotorista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mulacar/imagens/User-Clients-icon-24px.png"))); // NOI18N
        jButtonInserirMotorista.setText("Inserir");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Dados Do Motorista");

        jButtonBuscarMotorista.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonBuscarMotorista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mulacar/imagens/search-icon-24px.png"))); // NOI18N
        jButtonBuscarMotorista.setText("Buscar");

        jScrollPaneDadosDoCliente1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Do Cliente"));

        jTextAreaDadosDoCliente1.setColumns(20);
        jTextAreaDadosDoCliente1.setRows(5);
        jScrollPaneDadosDoCliente1.setViewportView(jTextAreaDadosDoCliente1);

        jTableDadosDoCliente1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("")));
        jTableDadosDoCliente1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "CPF / CPNP", "Nome / Razão Social", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneListaDeClientes1.setViewportView(jTableDadosDoCliente1);
        if (jTableDadosDoCliente1.getColumnModel().getColumnCount() > 0) {
            jTableDadosDoCliente1.getColumnModel().getColumn(0).setMinWidth(50);
            jTableDadosDoCliente1.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTableDadosDoCliente1.getColumnModel().getColumn(0).setMaxWidth(50);
            jTableDadosDoCliente1.getColumnModel().getColumn(1).setMinWidth(200);
            jTableDadosDoCliente1.getColumnModel().getColumn(1).setPreferredWidth(200);
            jTableDadosDoCliente1.getColumnModel().getColumn(1).setMaxWidth(200);
            jTableDadosDoCliente1.getColumnModel().getColumn(3).setMinWidth(30);
            jTableDadosDoCliente1.getColumnModel().getColumn(3).setPreferredWidth(30);
            jTableDadosDoCliente1.getColumnModel().getColumn(3).setMaxWidth(30);
        }

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox1.setText("Cliente é o Motorista");

        javax.swing.GroupLayout jPanelDadosDoMotoristaLayout = new javax.swing.GroupLayout(jPanelDadosDoMotorista);
        jPanelDadosDoMotorista.setLayout(jPanelDadosDoMotoristaLayout);
        jPanelDadosDoMotoristaLayout.setHorizontalGroup(
            jPanelDadosDoMotoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosDoMotoristaLayout.createSequentialGroup()
                .addGroup(jPanelDadosDoMotoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCpfCnpj1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel73, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadosDoMotoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDadosDoMotoristaLayout.createSequentialGroup()
                        .addComponent(jLabel74, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelDadosDoMotoristaLayout.createSequentialGroup()
                        .addComponent(jTextFieldNomeCliente1)
                        .addGap(203, 203, 203)))
                .addComponent(jButtonBuscarMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButtonInserirMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelDadosDoMotoristaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(485, 485, 485))
            .addGroup(jPanelDadosDoMotoristaLayout.createSequentialGroup()
                .addComponent(jScrollPaneListaDeClientes1, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadosDoMotoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDadosDoMotoristaLayout.createSequentialGroup()
                        .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(252, 252, 252))
                    .addComponent(jScrollPaneDadosDoCliente1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)))
        );
        jPanelDadosDoMotoristaLayout.setVerticalGroup(
            jPanelDadosDoMotoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosDoMotoristaLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGroup(jPanelDadosDoMotoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDadosDoMotoristaLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanelDadosDoMotoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel74)
                            .addComponent(jLabel73))
                        .addGap(1, 1, 1)
                        .addGroup(jPanelDadosDoMotoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCpfCnpj1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNomeCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelDadosDoMotoristaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDadosDoMotoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonBuscarMotorista)
                            .addComponent(jButtonInserirMotorista)
                            .addComponent(jCheckBox1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadosDoMotoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneDadosDoCliente1)
                    .addComponent(jScrollPaneListaDeClientes1, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("", jPanelDadosDoMotorista);

        jPanelDadosComplementares.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanelDadosComplementares.setPreferredSize(new java.awt.Dimension(1137, 434));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Dados Complementares");

        jLabel7.setText("Situação do Tanque:");

        jLabel8.setText("Data da Retirada:");

        jLabel9.setText("Data Devolução Prevista:");

        jTextAreaObservacao.setColumns(20);
        jTextAreaObservacao.setRows(5);
        jTextAreaObservacao.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jScrollPane1.setViewportView(jTextAreaObservacao);

        jLabel10.setText("KM Inicial:");

        jLabel12.setText("Valor Seguro:");

        jLabel13.setText("Data Cadastro:");

        jLabel14.setText("Usuário:");

        jButtonFinalizarCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mulacar/imagens/Ok-icon-24px.png"))); // NOI18N
        jButtonFinalizarCadastro.setText("Finalizar Cadastro");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Acessórios");

        jCheckBoxAcessorioCadeirinha.setText("Cadeirinha");

        jCheckBoxAcessorioSuporteParaBiciclet.setText("Suporte para Bicicleta");

        jTextAreaComposicaoValores.setColumns(20);
        jTextAreaComposicaoValores.setRows(5);
        jScrollPane2.setViewportView(jTextAreaComposicaoValores);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Observações");

        jButtonConfirmarComposicaoValores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mulacar/imagens/Button-Play-icon-24px.png"))); // NOI18N
        jButtonConfirmarComposicaoValores.setText("Confirmar");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Composição dos Valores");

        jLabel18.setText("Valor Locação:");

        jLabel19.setText("Valor Acessorios:");

        jLabel20.setText("Valor Caução:");

        javax.swing.GroupLayout jPanelDadosComplementaresLayout = new javax.swing.GroupLayout(jPanelDadosComplementares);
        jPanelDadosComplementares.setLayout(jPanelDadosComplementaresLayout);
        jPanelDadosComplementaresLayout.setHorizontalGroup(
            jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosComplementaresLayout.createSequentialGroup()
                .addGap(395, 395, 395)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelDadosComplementaresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldSituacaoDoTanque, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addComponent(jTextFieldDataDaRetirada)
                    .addComponent(jTextFieldDataDevolucaoPrevista)
                    .addComponent(jTextFieldKmInicial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDadosComplementaresLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(194, 194, 194))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDadosComplementaresLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(115, 115, 115)
                        .addComponent(jButtonConfirmarComposicaoValores)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDadosComplementaresLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanelDadosComplementaresLayout.createSequentialGroup()
                .addGroup(jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDadosComplementaresLayout.createSequentialGroup()
                        .addGap(337, 337, 337)
                        .addGroup(jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldValorCaucao, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jTextFieldValorLocacao)
                            .addComponent(jTextFieldValorSeguro)
                            .addComponent(jTextFieldValorAcessorios)))
                    .addGroup(jPanelDadosComplementaresLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addGroup(jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelDadosComplementaresLayout.createSequentialGroup()
                                .addComponent(jCheckBoxAcessorioCadeirinha)
                                .addGap(57, 57, 57)
                                .addComponent(jCheckBoxAcessorioSuporteParaBiciclet))
                            .addGroup(jPanelDadosComplementaresLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(70, 70, 70)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonFinalizarCadastro)
                        .addGroup(jPanelDadosComplementaresLayout.createSequentialGroup()
                            .addGroup(jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel14)
                                .addComponent(jLabel13))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldUsuarioCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanelDadosComplementaresLayout.setVerticalGroup(
            jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosComplementaresLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGroup(jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDadosComplementaresLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextFieldSituacaoDoTanque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(jTextFieldValorLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextFieldDataDaRetirada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldValorSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextFieldDataDevolucaoPrevista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldValorAcessorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTextFieldKmInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(jTextFieldValorCaucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelDadosComplementaresLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(jButtonConfirmarComposicaoValores))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addGroup(jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDadosComplementaresLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addGroup(jPanelDadosComplementaresLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxAcessorioCadeirinha, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jCheckBoxAcessorioSuporteParaBiciclet)))))
                    .addGroup(jPanelDadosComplementaresLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldUsuarioCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonFinalizarCadastro))
        );

        jTabbedPane1.addTab("", jPanelDadosComplementares);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mulacar/imagens/Travel-BMV-icon-128px-MulaCar.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Locação de Veículos");

        jButtonSelecaoVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mulacar/imagens/Arrow-previous-icon64px in.png"))); // NOI18N
        jButtonSelecaoVeiculo.setText("Seleção do Veiculo");
        jButtonSelecaoVeiculo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSelecaoVeiculo.setMaximumSize(new java.awt.Dimension(110, 90));
        jButtonSelecaoVeiculo.setMinimumSize(new java.awt.Dimension(110, 90));
        jButtonSelecaoVeiculo.setPreferredSize(new java.awt.Dimension(110, 90));
        jButtonSelecaoVeiculo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonSelecaoVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelecaoVeiculoActionPerformed(evt);
            }
        });

        jButtonDadosDoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mulacar/imagens/arrow-next-icon-64px.png"))); // NOI18N
        jButtonDadosDoCliente.setText("Dados do Cliente");
        jButtonDadosDoCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonDadosDoCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonDadosDoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDadosDoClienteActionPerformed(evt);
            }
        });

        jButtonDadosDoMotorista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mulacar/imagens/arrow-next-icon-64px.png"))); // NOI18N
        jButtonDadosDoMotorista.setText("Dados do Motorista");
        jButtonDadosDoMotorista.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonDadosDoMotorista.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonDadosDoMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDadosDoMotoristaActionPerformed(evt);
            }
        });

        jButtonDadosComplementares.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mulacar/imagens/Arrow-next-icon-64pxfim.png"))); // NOI18N
        jButtonDadosComplementares.setText("Dados Complementares");
        jButtonDadosComplementares.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonDadosComplementares.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonDadosComplementares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDadosComplementaresActionPerformed(evt);
            }
        });

        jButtonFecharLocacao.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jButtonFecharLocacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mulacar/imagens/Actions-window-close-icon-24px.png"))); // NOI18N
        jButtonFecharLocacao.setText("Fechar");
        jButtonFecharLocacao.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonFecharLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharLocacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jButtonSelecaoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jButtonDadosDoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jButtonDadosDoMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jButtonDadosComplementares, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonFecharLocacao)
                        .addContainerGap())))
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1132, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonDadosDoCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDadosDoMotorista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButtonSelecaoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addComponent(jButtonFecharLocacao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButtonDadosComplementares, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1148, 643));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSelecaoVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelecaoVeiculoActionPerformed
        // TODO add your handling code here:
        this.jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButtonSelecaoVeiculoActionPerformed

    private void jButtonDadosDoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDadosDoClienteActionPerformed
        // TODO add your handling code here:
        this.jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jButtonDadosDoClienteActionPerformed

    private void jButtonDadosDoMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDadosDoMotoristaActionPerformed
        // TODO add your handling code here:
        this.jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jButtonDadosDoMotoristaActionPerformed

    private void jButtonDadosComplementaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDadosComplementaresActionPerformed
        // TODO add your handling code here:
        this.jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_jButtonDadosComplementaresActionPerformed

    private void jComboBoxSelecaoModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSelecaoModeloActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBoxSelecaoModeloActionPerformed

    private void jComboBoxSelecaoMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSelecaoMarcaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBoxSelecaoMarcaActionPerformed

    private void jButtonBuscarVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarVeiculosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBuscarVeiculosActionPerformed

    private void jButtonFecharLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharLocacaoActionPerformed
        // TODO add your handling code here:
        try {
            this.dispose();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonFecharLocacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LocacaoVeiculosApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LocacaoVeiculosApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LocacaoVeiculosApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LocacaoVeiculosApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LocacaoVeiculosApp dialog = new LocacaoVeiculosApp(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscarCliente;
    private javax.swing.JButton jButtonBuscarMotorista;
    private javax.swing.JButton jButtonBuscarVeiculos;
    private javax.swing.JButton jButtonConfirmarComposicaoValores;
    private javax.swing.JButton jButtonDadosComplementares;
    private javax.swing.JButton jButtonDadosDoCliente;
    private javax.swing.JButton jButtonDadosDoMotorista;
    private javax.swing.JButton jButtonFecharLocacao;
    private javax.swing.JButton jButtonFinalizarCadastro;
    private javax.swing.JButton jButtonInserirCliente;
    private javax.swing.JButton jButtonInserirMotorista;
    private javax.swing.JButton jButtonSelecaoVeiculo;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBoxAcessorioCadeirinha;
    private javax.swing.JCheckBox jCheckBoxAcessorioSuporteParaBiciclet;
    private javax.swing.JComboBox jComboBoxSelecaoCategoria;
    private javax.swing.JComboBox jComboBoxSelecaoMarca;
    private javax.swing.JComboBox jComboBoxSelecaoModelo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelDadosComplementares;
    private javax.swing.JPanel jPanelDadosDoCliente;
    private javax.swing.JPanel jPanelDadosDoMotorista;
    private javax.swing.JPanel jPanelSelecaoDoVeiculo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPaneDadosDoCliente;
    private javax.swing.JScrollPane jScrollPaneDadosDoCliente1;
    private javax.swing.JScrollPane jScrollPaneListaDeClientes;
    private javax.swing.JScrollPane jScrollPaneListaDeClientes1;
    private javax.swing.JScrollPane jScrollPaneListaDeVeiculo;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableDadosDoCliente;
    private javax.swing.JTable jTableDadosDoCliente1;
    private javax.swing.JTable jTableListaDeVeiculos;
    private javax.swing.JTextArea jTextAreaComposicaoValores;
    private javax.swing.JTextArea jTextAreaDadosDoCliente;
    private javax.swing.JTextArea jTextAreaDadosDoCliente1;
    private javax.swing.JTextArea jTextAreaObservacao;
    private javax.swing.JTextField jTextFieldCpfCnpj;
    private javax.swing.JTextField jTextFieldCpfCnpj1;
    private javax.swing.JTextField jTextFieldDataCadastro;
    private javax.swing.JTextField jTextFieldDataDaRetirada;
    private javax.swing.JTextField jTextFieldDataDevolucaoPrevista;
    private javax.swing.JTextField jTextFieldKmInicial;
    private javax.swing.JTextField jTextFieldNomeCliente;
    private javax.swing.JTextField jTextFieldNomeCliente1;
    private javax.swing.JTextField jTextFieldRazaoSocial;
    private javax.swing.JTextField jTextFieldSituacaoDoTanque;
    private javax.swing.JTextField jTextFieldUsuarioCadastro;
    private javax.swing.JTextField jTextFieldValorAcessorios;
    private javax.swing.JTextField jTextFieldValorCaucao;
    private javax.swing.JTextField jTextFieldValorLocacao;
    private javax.swing.JTextField jTextFieldValorSeguro;
    // End of variables declaration//GEN-END:variables
}
