/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.mulacar.app;

import br.com.mulacar.bll.LocacaoBll;
import br.com.mulacar.model.Locacao;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author roger
 */
public class RelatorioDeLocacoesApp extends javax.swing.JDialog {

    private LocacaoBll locacaoBll;
    private Locacao locacao;

    /**
     * Creates new form RelatorioDeLocacoesApp
     */
    public RelatorioDeLocacoesApp(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        locacaoBll = new LocacaoBll();

    }

    public static String convertDate(Date dtConsulta) {
        try {
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy", new Locale("pt", "BR"));
            return formato.format(dtConsulta);
        } catch (Exception erro) {
            erro.printStackTrace();
            return null;
        }
    }

    private void imprimirLocacoes(List<Locacao> listaLocacao) throws Exception {
        DefaultTableModel model = (DefaultTableModel) jTableRelatorioDeLocacoaes.getModel();
        model.setNumRows(0);
        locacaoBll.ordenaListaLocacoes(listaLocacao);
        for (int pos = 0; pos < listaLocacao.size(); pos++) {
            String[] linha = new String[18];
            Locacao locacao = listaLocacao.get(pos);
            linha[0] = locacao.getId() + "";
            if (locacao.getCliente().getNome().equalsIgnoreCase("null")
                    && locacao.getCliente().getNomeFantasia().equalsIgnoreCase("null")) {
                linha[1] = locacao.getCliente().getRazaoSocial().toUpperCase();
            } else {
                linha[1] = locacao.getCliente().getNome().toUpperCase();
            }
            linha[2] = locacao.getCliente().getCpfCnpj();
            linha[3] = locacao.getMotorista().getNome().toUpperCase();
            linha[4] = locacao.getMotorista().getCpf();
            linha[5] = locacao.getVeiculo().getPlaca().toUpperCase();
            linha[6] = locacao.getUsuario().getNome().toUpperCase();
            linha[7] = String.format("%.2f", locacao.getValorMulta());
            if (locacao.isTanqueCheio()) {
                linha[8] = "SIM";
            } else {
                linha[8] = "NÃO";
            }
            linha[9] = convertDate(locacao.getDataRetirada());
            linha[10] = convertDate(locacao.getDataDevolucaoPrevista());
            linha[11] = locacao.getKmInicial();
            linha[12] = locacao.getObservacoes();
            linha[13] = String.format("%.2f", locacao.getValorTotalAcessorios());
            linha[14] = String.format("%.2f", locacao.getValorTotalLocacao());
            linha[15] = String.format("%.2f", locacao.getValorSeguro());
            linha[16] = String.format("%.2f", locacao.getValorCaucao());
            linha[17] = locacao.getStatus().toString();
            model.addRow(linha);

            jTextFieldQuantRegistros.setText(listaLocacao.size() + "");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelRelatorioDeLocacoes = new javax.swing.JPanel();
        jTextFieldCampoDePesquisa = new javax.swing.JTextField();
        jButtonBuscarLocacoes = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRelatorioDeLocacoaes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldQuantRegistros = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatório de Locações de Veiculos - LOCADORA MULACAR");
        setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        setResizable(false);

        jPanelRelatorioDeLocacoes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonBuscarLocacoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mulacar/imagens/search-icon-16px_1.png"))); // NOI18N
        jButtonBuscarLocacoes.setText("Buscar");
        jButtonBuscarLocacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarLocacoesActionPerformed(evt);
            }
        });

        jTableRelatorioDeLocacoaes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Cliente", "CPF do Cliente", "Motorista", "CPF do Motorista", "Placa Do Veic.", "Usuário", "Multa", "Tanque Cheio ?", "Data Retirada", "Data Dev. Prevista", "Km Inicial", "Observações", "Valor Acessórios", "Valor Locação", "Valor Seguro", "Valor Caução", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTableRelatorioDeLocacoaes);
        if (jTableRelatorioDeLocacoaes.getColumnModel().getColumnCount() > 0) {
            jTableRelatorioDeLocacoaes.getColumnModel().getColumn(0).setMinWidth(50);
            jTableRelatorioDeLocacoaes.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTableRelatorioDeLocacoaes.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        jLabel1.setText("Quant.Registros:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mulacar/imagens/Actions-window-close-icon-16px.png"))); // NOI18N
        jButton1.setText("Fechar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRelatorioDeLocacoesLayout = new javax.swing.GroupLayout(jPanelRelatorioDeLocacoes);
        jPanelRelatorioDeLocacoes.setLayout(jPanelRelatorioDeLocacoesLayout);
        jPanelRelatorioDeLocacoesLayout.setHorizontalGroup(
            jPanelRelatorioDeLocacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRelatorioDeLocacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRelatorioDeLocacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRelatorioDeLocacoesLayout.createSequentialGroup()
                        .addGap(0, 680, Short.MAX_VALUE)
                        .addComponent(jTextFieldCampoDePesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBuscarLocacoes))
                    .addGroup(jPanelRelatorioDeLocacoesLayout.createSequentialGroup()
                        .addGroup(jPanelRelatorioDeLocacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelRelatorioDeLocacoesLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(7, 7, 7)
                                .addComponent(jTextFieldQuantRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)))
                        .addContainerGap())))
        );
        jPanelRelatorioDeLocacoesLayout.setVerticalGroup(
            jPanelRelatorioDeLocacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRelatorioDeLocacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRelatorioDeLocacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBuscarLocacoes)
                    .addComponent(jTextFieldCampoDePesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelRelatorioDeLocacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldQuantRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelRelatorioDeLocacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelRelatorioDeLocacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarLocacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarLocacoesActionPerformed
        // TODO add your handling code here:
        try {
            imprimirLocacoes(locacaoBll.getConsultaLocacoes());

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Atenção ao botão buscar !!!\n" + erro.getMessage());
        }
    }//GEN-LAST:event_jButtonBuscarLocacoesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatorioDeLocacoesApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatorioDeLocacoesApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatorioDeLocacoesApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorioDeLocacoesApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RelatorioDeLocacoesApp dialog = new RelatorioDeLocacoesApp(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBuscarLocacoes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelRelatorioDeLocacoes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRelatorioDeLocacoaes;
    private javax.swing.JTextField jTextFieldCampoDePesquisa;
    private javax.swing.JTextField jTextFieldQuantRegistros;
    // End of variables declaration//GEN-END:variables
}
