/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.mulacar.app;

import br.com.mulacar.bll.MotoristaBll;
import br.com.mulacar.dal.Imagem_Adapter;
import br.com.mulacar.interfaces.Interface_ExibirImagem;
import br.com.mulacar.model.Motorista;
import java.awt.Image;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author roger
 */
public class RelatorioDeMotoristaApp extends javax.swing.JDialog {

    private MotoristaBll motoristaBll;
    private SimpleDateFormat dataFormt;

    /**
     * Creates new form RelatorioDeMotoristaApp
     */
    public RelatorioDeMotoristaApp(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jTextFieldDigitarDadosParaPesquisa.requestFocus();

        motoristaBll = new MotoristaBll();
        dataFormt = new SimpleDateFormat("dd/MM/yyyy");

    }

    private void imprimirRelatorioDeMotoristas(List<Motorista> lista) throws Exception {
        DefaultTableModel model = (DefaultTableModel) jTableMotoristas.getModel();
        model.setNumRows(0);
        motoristaBll.ordenaListaMotoristas(lista);
        for (int pos = 0; pos < lista.size(); pos++) {
            String[] linha = new String[8];
            Motorista motorista = lista.get(pos);
            linha[0] = "" + motorista.getId();
            linha[1] = motorista.getNome().toUpperCase();
            linha[2] = motorista.getCpf();
            linha[3] = motorista.getRg();
            linha[4] = motorista.getOrgaoEmissor().toUpperCase();
            linha[5] = motorista.getNumeroCnh();
            linha[6] = dataFormt.format(motorista.getDataValidadeCnh());
            linha[7] = motorista.getCategoriaCnh().toString();

            model.addRow(linha);
        }
        jTextFieldQuantRegistros.setText("" + lista.size());
    }

    private void exibirFotoDaCnh(int codigo) throws Exception {
        if (codigo > 0) {

            Motorista motorista = new Motorista(codigo);
            Motorista mot = motoristaBll.getMotoristaPorId(motorista);
            //jLabelExibirFotoDaCNH.setIcon(motoristaBll.exibirImagem(mot));

            Interface_ExibirImagem exibir_Adapter = new Imagem_Adapter();
            jLabelExibirFotoDaCNH.setIcon(exibir_Adapter.exibirImagem(mot));
        } else {
            JOptionPane.showMessageDialog(null, "Nenhum Registro Encontrado!\nVerifique !");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelRelatorioDeMotoristas = new javax.swing.JPanel();
        jTextFieldDigitarDadosParaPesquisa = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMotoristas = new javax.swing.JTable();
        jLabelExibirFotoDaCNH = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldQuantRegistros = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatório de Motoristas");
        setResizable(false);

        jPanelRelatorioDeMotoristas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mulacar/imagens/search-icon-24px.png"))); // NOI18N
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jTableMotoristas.setAutoCreateRowSorter(true);
        jTableMotoristas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód.", "Nome", "CPF", "RG", "Orgão Emissor", "Núm. CNH", "Validade CNH", "Categoria CNH"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableMotoristas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTableMotoristasMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTableMotoristas);
        if (jTableMotoristas.getColumnModel().getColumnCount() > 0) {
            jTableMotoristas.getColumnModel().getColumn(0).setMinWidth(50);
            jTableMotoristas.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTableMotoristas.getColumnModel().getColumn(0).setMaxWidth(50);
            jTableMotoristas.getColumnModel().getColumn(4).setMinWidth(75);
            jTableMotoristas.getColumnModel().getColumn(4).setPreferredWidth(75);
            jTableMotoristas.getColumnModel().getColumn(4).setMaxWidth(75);
            jTableMotoristas.getColumnModel().getColumn(7).setMinWidth(70);
            jTableMotoristas.getColumnModel().getColumn(7).setPreferredWidth(70);
            jTableMotoristas.getColumnModel().getColumn(7).setMaxWidth(70);
        }

        jLabelExibirFotoDaCNH.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jLabelExibirFotoDaCNH.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jLabel3.setText("Imagem da CNH do motorista");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jLabel4.setText("Quant.Registros:");

        jTextFieldQuantRegistros.setEditable(false);

        jButton1.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mulacar/imagens/Actions-window-close-icon-24px.png"))); // NOI18N
        jButton1.setText("Fechar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRelatorioDeMotoristasLayout = new javax.swing.GroupLayout(jPanelRelatorioDeMotoristas);
        jPanelRelatorioDeMotoristas.setLayout(jPanelRelatorioDeMotoristasLayout);
        jPanelRelatorioDeMotoristasLayout.setHorizontalGroup(
            jPanelRelatorioDeMotoristasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRelatorioDeMotoristasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRelatorioDeMotoristasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanelRelatorioDeMotoristasLayout.createSequentialGroup()
                        .addComponent(jTextFieldDigitarDadosParaPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                    .addGroup(jPanelRelatorioDeMotoristasLayout.createSequentialGroup()
                        .addGroup(jPanelRelatorioDeMotoristasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelRelatorioDeMotoristasLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldQuantRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(98, 98, 98))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRelatorioDeMotoristasLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jLabelExibirFotoDaCNH, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanelRelatorioDeMotoristasLayout.createSequentialGroup()
                .addGap(203, 772, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(14, 14, 14))
        );
        jPanelRelatorioDeMotoristasLayout.setVerticalGroup(
            jPanelRelatorioDeMotoristasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRelatorioDeMotoristasLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanelRelatorioDeMotoristasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDigitarDadosParaPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelRelatorioDeMotoristasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRelatorioDeMotoristasLayout.createSequentialGroup()
                        .addGroup(jPanelRelatorioDeMotoristasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldQuantRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(99, 99, 99)
                        .addComponent(jLabel3))
                    .addComponent(jLabelExibirFotoDaCNH, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelRelatorioDeMotoristas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelRelatorioDeMotoristas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
        try {
            String string = jTextFieldDigitarDadosParaPesquisa.getText().trim();
            if (string.isEmpty()) {

                imprimirRelatorioDeMotoristas(motoristaBll.getConsultaMotoristas());

            } else {

                imprimirRelatorioDeMotoristas(motoristaBll.pesquisarMotorista(string));
            }
            jTextFieldDigitarDadosParaPesquisa.requestFocus();

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Atenção ao Botão Buscar!!!\n"
                    + erro.getMessage());
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jTableMotoristasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMotoristasMouseReleased
        // TODO add your handling code here:
        try {
            int linha = jTableMotoristas.getSelectedRow();
            Integer codigo = Integer.parseInt(jTableMotoristas.getValueAt(linha, 0).toString());

            exibirFotoDaCnh(codigo);

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Atenção ao click na tabela de motoristas\n" + erro.getMessage());
        }
    }//GEN-LAST:event_jTableMotoristasMouseReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatorioDeMotoristaApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatorioDeMotoristaApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatorioDeMotoristaApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorioDeMotoristaApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RelatorioDeMotoristaApp dialog = new RelatorioDeMotoristaApp(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelExibirFotoDaCNH;
    private javax.swing.JPanel jPanelRelatorioDeMotoristas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMotoristas;
    private javax.swing.JTextField jTextFieldDigitarDadosParaPesquisa;
    private javax.swing.JTextField jTextFieldQuantRegistros;
    // End of variables declaration//GEN-END:variables
}
